# Generated by Django 3.0.8 on 2020-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
